Add note that login screen is optional
Banno/consumer-api-openid-connect-example pull request #2
Opened 2019-11-07 23:44 UTC by DevWithTheHair

The example shows a dedicated login screen (`login.html`). This is an optional step for customers, who can redirect users to Banno for authentication instead.

The updated login screen now looks like this:
![Screen Shot 2019-11-07 at 3 41 23 PM](https://user-images.githubusercontent.com/31429468/68437332-7a20e900-0175-11ea-9a07-66bac0119b3d.png)

2019-11-15 21:00 UTC, ChadKillingsworth requested changes
Based off a review of our implementation I had today - we need to update that note. It needs to specifically call out that in the auto-redirect case, a prevention mechanism must be in place for cross site request forgery attacks.

2019-11-15 21:50 UTC, DevWithTheHair commented
@ChadKillingsworth is there some specific advice or resources that we could point to that will help folks understand their implementation options?

2019-11-23 00:33 UTC, DevWithTheHair commented
@ChadKillingsworth I've updated the PR with some additional test about Cross-Site Request Forgery attacks.

2019-12-18 21:36 UTC, ChadKillingsworth approved these changes

2019-12-18 23:26 UTC, merged